# Generated by Django 5.0.1 on 2024-02-08 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0002_alter_student_email_alter_student_phone'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='Student',
        ),
    ]
